### ISSUE TITLE
잘못된 지하철역명을 입력했을 떄 error처리 문제

### ISSUE THREAD

**Issue by david600320** [yudong80/flutter_programming#1]
유동환님의 플러터책보고 공공API 앱을 따라해 보고 있습니다.  
( Android , 갤탭)

Issue :  지하철실시간정보 ( page_subway_info.dart )  를 따라하는 과정에서 , 지하철역 이름을 전혀 엉뚱하게 입력해 응답된 data가 없는 경우의 처리부가 전혀 동작되고 있지 않습니다. 

step 1 : 광화문 , 시청등 입력 ( 정상 )
step 2:  뉴욕역 입력 -> error 

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("status")
....<생략>....

감사합니다. 

david600320@hotmail.com

**Comment by oroi1991** [comment]
6장 예제에서 지하철공공데이터 가져오는 부부에서  Unexpected character 오류가 발생 합니다.

String responseBody = response.body;
var json = jsonDecode(responseBody);

responseBody 에는 정상적으로 보이는 xml 데이터가 있는데,
jsonDecode 될때 오류가 납니다. 뭐가 문제일까요?

**Comment by yudong80** [comment]
안녕하세요 유동환입니다.
해보고 답글 달께요~

**Comment by david600320** [comment]
제가 휴가중이어서 이제야 회신합니다.
감사합니다.

________________________________
보낸 사람: Dong Hwan Yu <notifications@github.com>
보낸 날짜: 2020년 8월 4일 화요일 오전 1:48
받는 사람: yudong80/flutter_programming <flutter_programming@noreply.github.com>
참조: david600320 <david600320@hotmail.com>; Author <author@noreply.github.com>
제목: Re: [yudong80/flutter_programming] 잘못된 지하철역명을 입력했을 떄 error처리 문제 (#1)


안녕하세요 유동환입니다.
해보고 답글 달께요~

**Comment by yudong80** [comment]
@david600320  님 확인해보니, "뉴욕"과 같이 오류가 발생할 때의 json 양식이 변경되었습니다. 
정상일때의 json: 
res >> {"errorMessage":{"status":200,"code":"INFO-000","message":"정상 처리되었습니다.","link":"","developerMessage":"","total":4}, <하략> 

비정상일때의 json: 
res >> {"status":500,"code":"INFO-200","message":"해당하는 데이터가 없습니다.","link":"","developerMessage":"","total":0}

이렇게 변경하면 됩니다. 
BEFORE: 
    if (errorMessage['status'] != api.STATUS_OK) {
      setState(() {
        final String errMessage = errorMessage['message'];

AFTER: 
    if (errorMessage == null || errorMessage['status'] != api.STATUS_OK) {
      setState(() {
        final String errMessage = json['message'];

패치 올려둘께요

**Comment by yudong80** [comment]
@oroi1991 님 같은 문제로 보입니다. 

공공 API의 오류메시지 오는 양식이 변경되었네요 / 최신으로 땡겨보세요

**Comment by yudong80** [comment]
수정 패치 올렸습니다 :-)

https://github.com/yudong80/flutter_programming/commit/07df390a3698f2745a44e03f022f79a35c227f1d

**Comment by david600320** [comment]
제공해 주신 좋은 예제로 Flutter를 이해하는데 많은 도움이 되었습니다.
감사합니다.

________________________________
보낸 사람: Dong Hwan Yu <notifications@github.com>
보낸 날짜: 2020년 8월 10일 월요일 오후 9:55
받는 사람: yudong80/flutter_programming <flutter_programming@noreply.github.com>
참조: david600320 <david600320@hotmail.com>; Mention <mention@noreply.github.com>
제목: Re: [yudong80/flutter_programming] 잘못된 지하철역명을 입력했을 떄 error처리 문제 (#1)


@david600320<https://github.com/david600320> 님 확인해보니, "뉴욕"과 같이 오류가 발생할 때의 json 양식이 변경되었습니다.
정상일때의 json:
res >> {"errorMessage":{"status":200,"code":"INFO-000","message":"정상 처리되었습니다.","link":"","developerMessage":"","total":4}, <하략>

비정상일때의 json:
res >> {"status":500,"code":"INFO-200","message":"해당하는 데이터가 없습니다.","link":"","developerMessage":"","total":0}

이렇게 변경하면 됩니다.
BEFORE:
if (errorMessage['status'] != api.STATUS_OK) {
setState(() {
final String errMessage = errorMessage['message'];

AFTER:
if (errorMessage == null || errorMessage['status'] != api.STATUS_OK) {
setState(() {
final String errMessage = json['message'];

패치 올려둘께요
